### ISSUE TITLE
Trigger build without creating it

### ISSUE THREAD

**Issue by strarsis** [RyanTheAllmighty/Docker-Hub-API#11]
It is also possible to trigger a build in Docker Hub web UI without creating it first.
This is especially useful with https://github.com/docker/hub-feedback/issues/520 not resolved yet.
Otherwise the build has to be created first, triggered and then removed again.
This would also increase the Web UI feature vs API parity.

**Comment by RyanTheAllmighty** [comment]
Coming back to this now, it looks as though it should work as expected with the existing `triggerBuild(username, name, {"source_name":"asd","source_type":"Branch","dockerfile_location":"/"})`

If this is still an issue, such as I'm not understanding the issue (it has been 2 years sorry), please let me know
