### ISSUE TITLE
createAutomatedbuild return error

### ISSUE THREAD

**Issue by forumi072issue** [RyanTheAllmighty/Docker-Hub-API#14]
Hi
I use this awesome tool for create automated build.
But when I create repository, It returns error. (Static repository great works)

I use bitbucket and use below code for create my repository, but body.details returns '{ build_tags: [ 'This field is required.' ] }'

```
let dockerHubAPI = require('docker-hub-api');
dockerHubAPI.login(process.env.USER_NAME, process.env.USER_PASSWD).then(function(info) {
console.log(info); //Logins OK
});

//After Log in
var details={ 'build_tags': [ { 'name': 'latest', 'source_type': 'Branch', 'source_name': 'master', 'dockerfile_location': '/' } ], 'description': 'test', 'is_private': false, 'provider': 'bitbucket', 'vcs_repo_name': 'username/repository' }; //For create basic build option
dockerHubAPI.createAutomatedBuild('myaccount', 'test', details).then(function(resolve,reject) {
console.log(reject);
console.log(resolve);
}).catch((error) => {
    console.log(error);
    error;
});
```

I was give build_tags and according to manual, it can void (then set default).

Is this docker-hub-api or docker-hub bug? Other wise my config fault?

**Comment by RyanTheAllmighty** [comment]
Yeah definately an issue. I've updated the example in the README and fixed it so the function will just  pass in your provided details which overwrites the defaults.
