### ISSUE TITLE
Delete Tags Not Working

### ISSUE THREAD

**Issue by samueljmello** [RyanTheAllmighty/Docker-Hub-API#17]
Deleting tags is not working for me. I think the issue is that the URL isn't correct for the current Docker Hub API.

https://github.com/RyanTheAllmighty/Docker-Hub-API/blob/b00c8adf6bc1184a997263354762ea37533e2af1/src/api.js#L629

`repositories/${username}/${name}/autobuild/tags/${id}`

...is the URL being called. I changed it to:

`repositories/${username}/${name}/tags/${id}`

...and was able to get it working, but **only after** also changing `id` to be the name of the tag instead of the ID.

Hopefully this helps. Or maybe I'm the only person experiencing this issue.

**Comment by RyanTheAllmighty** [comment]
Are you trying to delete a tag such as `latest` or a build tag used in automated repositories?

For instance `deleteTag()` function refers to tags, for example, at https://hub.docker.com/r/ryantheallmighty/docker-hub-api/tags/

`deleteBuildTag()` are those, as shown at https://docs.docker.com/docker-hub/builds/#create-an-automated-build for which branches and tags from github refer to which tag in an automated build.

From my testing it looks like it works still for both scenarios.

Let me know if that doesn't clear it up
