### ISSUE TITLE
Add support for Automated Build functions

### ISSUE THREAD

**Issue by strarsis** [RyanTheAllmighty/Docker-Hub-API#2]
It would be great when one can access the automated build functions of Dockerhub, 
like triggering builds or checking previous builds (like failed builds).

**Comment by RyanTheAllmighty** [comment]
Sure thing, sounds reasonable. Think I skipped it due to not having a build to test against, but now I do I can add those methods in.

**Comment by RyanTheAllmighty** [comment]
Alright this should cover all the automated build functions. Will be available as version 0.5.0 in the next couple days once I complete some more of the API.

**Comment by strarsis** [comment]
Awesome! :+1:
