### ISSUE TITLE
set repository description is  missing is_private option.

### ISSUE THREAD

**Issue by dgoo2308** [RyanTheAllmighty/Docker-Hub-API#20]
The [setrepositorydescription](https://github.com/RyanTheAllmighty/Docker-Hub-API#setrepositorydescriptionusername-name-descriptions) the api misses  `is_private`.

Seems the DockerHub api for `set repository` is the same as `create repository`:
```json
{
    description: 'Test',
    full_description: 'Test',
    is_private: false
}
```

**Comment by RyanTheAllmighty** [comment]
Interesting.

Just tried and you can alter the privacy of the repo this way.

You can also POST the following object:

```json
{
    "is_private": true
}
```

To `/repositories/${username}/${repository}/privacy/` to control that.

I'll add a `setPrivacy` method, but setting via a repository description method seems a bit odd doesn't it?

**Comment by dgoo2308** [comment]
Yes, bit odd.

anyhow, thought I report it here, I don't use your API, since I'm working in c,

but this seems the only place I could find some info regarding the Docker Hub API.
