### ISSUE TITLE
Are these official APIs?

### ISSUE THREAD

**Issue by kartikbb** [RyanTheAllmighty/Docker-Hub-API#23]
I could not find official documentation from DockerHub for these APIs. I believe you have inspected the APIs the DockerHub UI uses and implemented this library.
Am I right? If yes, then there is no official support for these APIs either. DockerHub has no official support for them and the library will break if and when they decide to change the APIs. Correct?

**Comment by RyanTheAllmighty** [comment]
Correct on all parts.
