### ISSUE TITLE
detail response is handled as an error without checking the error value

### ISSUE THREAD

**Issue by dozer75** [RyanTheAllmighty/Docker-Hub-API#24]
When a request returns detail, the API returns this as an error, which isn't always the case. It should check the error value.

A response with detail typical looks like this:

{"detail": "some message", "error": false}

I think that the code that parses this should check if error is true/false before rejecting it as an error.

**Comment by RyanTheAllmighty** [comment]
Looks like there are a bunch of places that use `detail` to describe an error without passing back an `error` parameter.

I can add in a check that will not throw an error if `error` is passed back as `false`, but since the api's aren't consistent, that's about all the checks that can be reliably added in

**Comment by RyanTheAllmighty** [comment]
@dozer75 do you have a specific example where I can see that detail is set, but error is false?

**Comment by dozer75** [comment]
@RyanTheAllmighty The `logout` method is one I found. You don't have it in your package, but I'm using `makePostRequest` to do the call explicit, and it fails.

The response is { detail: "Logged out", error: false }

This [gist](https://gist.github.com/dozer75/a10bfba8fe21ff95d6439193086ed122) has some small gulp commands I'm using to keep my docker repository clean for old CI images where I log out after completion where I call logout.

**Comment by RyanTheAllmighty** [comment]
Alright so I've tested with logout and when error is passed back as `false` it now skips throwing an error.

I also added in a logout method, no params necessary.

Published as version `0.8.0` on npm
